/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as ApiConvertRouteImport } from './routes/api/convert'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardAffiliateRouteImport } from './routes/dashboard.affiliate'
import { Route as DashboardCampaignsRouteImport } from './routes/dashboard.campaigns'
import { Route as DashboardCommissionsRouteImport } from './routes/dashboard.commissions'
import { Route as DashboardLinksRouteImport } from './routes/dashboard.links'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardOffersRouteImport } from './routes/dashboard.offers'
import { Route as DashboardPayoutsRouteImport } from './routes/dashboard.payouts'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardVendorRouteImport } from './routes/dashboard.vendor'
import { Route as OffersSlugRouteImport } from './routes/offers.$slug'
import { Route as TCodeRouteImport } from './routes/t.$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConvertRoute = ApiConvertRouteImport.update({
  id: '/api/convert',
  path: '/api/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAffiliateRoute = DashboardAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsRoute = DashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommissionsRoute = DashboardCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLinksRoute = DashboardLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOffersRoute = DashboardOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPayoutsRoute = DashboardPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVendorRoute = DashboardVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => DashboardRoute,
} as any)
const OffersSlugRoute = OffersSlugRouteImport.update({
  id: '/offers/$slug',
  path: '/offers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TCodeRoute = TCodeRouteImport.update({
  id: '/t/$code',
  path: '/t/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/vendors': typeof VendorsRoute
  '/api/convert': typeof ApiConvertRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/affiliate': typeof DashboardAffiliateRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/commissions': typeof DashboardCommissionsRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/offers': typeof DashboardOffersRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vendor': typeof DashboardVendorRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/t/$code': typeof TCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/vendors': typeof VendorsRoute
  '/api/convert': typeof ApiConvertRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/affiliate': typeof DashboardAffiliateRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/commissions': typeof DashboardCommissionsRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/offers': typeof DashboardOffersRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vendor': typeof DashboardVendorRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/t/$code': typeof TCodeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/vendors': typeof VendorsRoute
  '/api/convert': typeof ApiConvertRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/affiliate': typeof DashboardAffiliateRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/commissions': typeof DashboardCommissionsRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/offers': typeof DashboardOffersRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vendor': typeof DashboardVendorRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/t/$code': typeof TCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/marketplace'
    | '/onboarding'
    | '/vendors'
    | '/api/convert'
    | '/dashboard/admin'
    | '/dashboard/affiliate'
    | '/dashboard/campaigns'
    | '/dashboard/commissions'
    | '/dashboard/links'
    | '/dashboard/notifications'
    | '/dashboard/offers'
    | '/dashboard/payouts'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/vendor'
    | '/offers/$slug'
    | '/t/$code'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-it-works'
    | '/login'
    | '/marketplace'
    | '/onboarding'
    | '/vendors'
    | '/api/convert'
    | '/dashboard/admin'
    | '/dashboard/affiliate'
    | '/dashboard/campaigns'
    | '/dashboard/commissions'
    | '/dashboard/links'
    | '/dashboard/notifications'
    | '/dashboard/offers'
    | '/dashboard/payouts'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/vendor'
    | '/offers/$slug'
    | '/t/$code'
    | '/dashboard'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/marketplace'
    | '/onboarding'
    | '/vendors'
    | '/api/convert'
    | '/dashboard/admin'
    | '/dashboard/affiliate'
    | '/dashboard/campaigns'
    | '/dashboard/commissions'
    | '/dashboard/links'
    | '/dashboard/notifications'
    | '/dashboard/offers'
    | '/dashboard/payouts'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/vendor'
    | '/offers/$slug'
    | '/t/$code'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OnboardingRoute: typeof OnboardingRoute
  VendorsRoute: typeof VendorsRoute
  ApiConvertRoute: typeof ApiConvertRoute
  OffersSlugRoute: typeof OffersSlugRoute
  TCodeRoute: typeof TCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/convert': {
      id: '/api/convert'
      path: '/api/convert'
      fullPath: '/api/convert'
      preLoaderRoute: typeof ApiConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/affiliate': {
      id: '/dashboard/affiliate'
      path: '/affiliate'
      fullPath: '/dashboard/affiliate'
      preLoaderRoute: typeof DashboardAffiliateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns': {
      id: '/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof DashboardCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/commissions': {
      id: '/dashboard/commissions'
      path: '/commissions'
      fullPath: '/dashboard/commissions'
      preLoaderRoute: typeof DashboardCommissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/links': {
      id: '/dashboard/links'
      path: '/links'
      fullPath: '/dashboard/links'
      preLoaderRoute: typeof DashboardLinksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/offers': {
      id: '/dashboard/offers'
      path: '/offers'
      fullPath: '/dashboard/offers'
      preLoaderRoute: typeof DashboardOffersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payouts': {
      id: '/dashboard/payouts'
      path: '/payouts'
      fullPath: '/dashboard/payouts'
      preLoaderRoute: typeof DashboardPayoutsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vendor': {
      id: '/dashboard/vendor'
      path: '/vendor'
      fullPath: '/dashboard/vendor'
      preLoaderRoute: typeof DashboardVendorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/offers/$slug': {
      id: '/offers/$slug'
      path: '/offers/$slug'
      fullPath: '/offers/$slug'
      preLoaderRoute: typeof OffersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$code': {
      id: '/t/$code'
      path: '/t/$code'
      fullPath: '/t/$code'
      preLoaderRoute: typeof TCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAffiliateRoute: typeof DashboardAffiliateRoute
  DashboardCampaignsRoute: typeof DashboardCampaignsRoute
  DashboardCommissionsRoute: typeof DashboardCommissionsRoute
  DashboardLinksRoute: typeof DashboardLinksRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOffersRoute: typeof DashboardOffersRoute
  DashboardPayoutsRoute: typeof DashboardPayoutsRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardVendorRoute: typeof DashboardVendorRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAffiliateRoute: DashboardAffiliateRoute,
  DashboardCampaignsRoute: DashboardCampaignsRoute,
  DashboardCommissionsRoute: DashboardCommissionsRoute,
  DashboardLinksRoute: DashboardLinksRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOffersRoute: DashboardOffersRoute,
  DashboardPayoutsRoute: DashboardPayoutsRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardVendorRoute: DashboardVendorRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  OnboardingRoute: OnboardingRoute,
  VendorsRoute: VendorsRoute,
  ApiConvertRoute: ApiConvertRoute,
  OffersSlugRoute: OffersSlugRoute,
  TCodeRoute: TCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
